### ISSUE TITLE
Version in Octane blueprint don't work with Pods structure 

### ISSUE THREAD

**Issue by schekin** [ember-cli/ember-cli-htmlbars#265]
Version in Octane blueprint don't work with Pods structure. If i am generate new component, generator put its in ui/components/navigation... and its not found. In version 3.1.0 worsk with Pods

**Comment by chancancode** [comment]
Do you mean pods or “module unification”? What are the full paths of the files and the relevant settings in your app? (eg podModulePrefix)

**Comment by chancancode** [comment]
I would also strongly recommend transitioning away from either by the way 😬

**Comment by chancancode** [comment]
@schekin we received a few reports that this issue is fixed (or that is not related to pods after all). See https://github.com/emberjs/ember.js/issues/18350#issuecomment-536406093. I also tried to reproduce it in ember-learn/super-rentals-tutorial#72 and everything seems to work correctly. If you are experiencing this issue please fork https://github.com/chancancode/super-rentals-pods-ish/ and see if you can make it fail.

Closing for now, but feel free to comment with more information and I can re-open!
