### ISSUE TITLE
does not contain a `default export`

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-cli-htmlbars#389]
After upgrading `ember-cli-htmlbars` from `4.0.8` to `4.1.0` I get a white screen of death in my app - with the error:

> Uncaught (in promise) Error: 'my-app/components/foo.js' does not contain a 'default export'. Did you forget to export the component class?

Where `my-app/components/foo.js` is provided to my app as re-export from an external addon.

**Comment by amk221** [comment]
(I narrowed this error down to `ember-cli-htmlbars` by individually upgrading the dependencies of my app until it broke)

**Comment by rwjblue** [comment]
Thank you for reporting! Do you happen to know which addon it is (so I can clone it and try it in a local test app also)?

**Comment by rwjblue** [comment]
Also, can you confirm that it worked fine in 4.0.8?

**Comment by rwjblue** [comment]
I think this block has to be removed:

https://github.com/ember-cli/ember-cli-htmlbars/blob/c8c7b2aa97898e6dd9325ff9d2c526962b2bfa6d/lib/colocated-broccoli-plugin.js#L153

In 4.0.8 we only did work when we found an HBS file, which meant that that error was only injected when the HBS file was right next to the component JS file. However, in 4.1.0+ we process “patches” of the full components/ directory instead. In this case, it means that we spot the `.js` file and attempt to process it but since their is no corresponding template we should have ignored it. 

I’ll get some additional tests added for reexport cases in the next hour or so.

**Comment by amk221** [comment]
- It was a couple of addons to be honest, here is [one](https://github.com/zestia/ember-expander).
- Yes it worked in 4.08
- OK, looks like you know what the issue is already anyway :D

**Comment by rwjblue** [comment]
Sorry for the troubles here, the fix is released in v4.1.1. Would y'all mind testing?

**Comment by amk221** [comment]
Works for me. 👍 Thanks!
